### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Gounlaf** [nacular/doodle#1]
Hi,

I've just found your project and I want to try it!
Unfortunately I can't install it. Both _maven_ & _jcenter_ are configured in repositories, but your artifacts can't be found.

I will try to install it as a third-party module and it should work.

Regards,

**Comment by pusolito** [comment]
Hi @Gounlaf, how are you specifying the dependency in your project?

I verified myself with a local project. And you can see that version 0.1.0 is currently in Maven Central: https://search.maven.org/search?q=io.nacular.doodle.

**Comment by Gounlaf** [comment]
Hi @pusolito,

I follow the documentation here https://nacular.github.io/doodle/#/installation
Setting up a new _multiplatform native_ project create the following _build.gradle.kts_

```gradle
plugins {
    kotlin("multiplatform") version "1.4.10"
    kotlin("plugin.serialization") version "1.4.10"
}

group = "me.florianlevis"
version = "1.0-SNAPSHOT"

repositories {
    jcenter()
    mavenCentral()
}

val doodleVersion = "0.1.0"

kotlin {
    val hostOs = System.getProperty("os.name")
    val isMingwX64 = hostOs.startsWith("Windows")
    val nativeTarget = when {
        hostOs == "Mac OS X" -> macosX64("native")
        hostOs == "Linux" -> linuxX64("native")
        isMingwX64 -> mingwX64("native")
        else -> throw GradleException("Host OS is not supported in Kotlin/Native.")
    }

    nativeTarget.apply {
        binaries {
            executable {
                entryPoint = "main"
            }
        }
    }

    js {}

    sourceSets {
        val nativeMain by getting {
            dependencies {
                implementation(kotlin("stdlib-common", org.jetbrains.kotlin.config.KotlinCompilerVersion.VERSION))
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.0-RC2")

                implementation ("io.nacular.doodle:core:$doodleVersion")
                implementation ("io.nacular.doodle:browser:$doodleVersion")
                implementation ("io.nacular.doodle:controls:$doodleVersion")
                implementation ("io.nacular.doodle:animation:$doodleVersion")
                implementation ("io.nacular.doodle:themes:$doodleVersion")
            }
        }

        val jsMain by getting { // with or without it doesn't work
            dependencies {
                implementation(kotlin("stdlib-js"))
            }
        }
    }
}
```

And the following error:

```
Could not resolve io.nacular.doodle:core:0.1.0.
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

So right now, I'm a bit confused about what's wrong =/

Thanks,

Regards.

**Comment by pusolito** [comment]
Yep; that's right. the framework is JS focused for now. Are you trying to build a web app? This is what Doodle can help with.

**Comment by Gounlaf** [comment]
> the framework is JS focused for now
OK; it was not very clear.

Thanks!

**Comment by pusolito** [comment]
You can use it in a multiplatform JS/Java project. This is useful if you'd like to write most (except launch logic) of your app in common code and test it using the JVM. This removes browser dependencies for these tests and speeds them up.

But, the target is still JS. And the launch logic of your app will need to be in jsMain if you use a multiplatform setup.

Thanks for the feedback. I'll improve the docs to make this clearer.
