### ISSUE TITLE
HelloWorld not working

### ISSUE THREAD

**Issue by bodiam** [nacular/doodle#12]
Hi there, I've finally started with Doodle, so I setup my project and tried the HelloWorld, but it doesn't compile. Could you please fix it?

There are 2 issues: 
* On line 23, there's a call to `application`. But there's no such thing as application. Maybe the import to `import io.nacular.doodle.application.application` is missing? Not sure.
* Another issue is: HelloWorld(display = instance()). What's `instance()`? It seems there's no reference to anything like instance(), and I can't find a suitable candidate.

Thanks,
Erik

**Comment by pusolito** [comment]
Thanks for catching/fixing this.

**Comment by pusolito** [comment]
Is the issue resolved with your the change in your PR?
