### ISSUE TITLE
Forms example?

### ISSUE THREAD

**Issue by bodiam** [nacular/doodle#18]
Hi, just wondering, but would you have an example with a form + layout? I'm looking for something like this, and I'm not sure if there's a formlayout or tablelayout which I could use for this?

![image](https://user-images.githubusercontent.com/46468/136682833-99072784-664a-4ff0-8fcb-3279430e5206.png)

**Comment by bodiam** [comment]
At the moment, I'm actually struggling to even add a button or a label to a view. I see a lot of examples with the render method, but how do I do something like:

```



```
        display += view {
            size   = display.size

           val label = Label("my text")
           val button = Button("my buttton") 

           // how to add these to the view?
```

**Comment by pusolito** [comment]
> Hi, just wondering, but would you have an example with a form + layout? I'm looking for something like this, and I'm not sure if there's a formlayout or tablelayout which I could use for this?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/46468/136682833-99072784-664a-4ff0-8fcb-3279430e5206.png)
> 
> 

This is achievable using a [`ConstraintLayout`](Core/src/commonMain/kotlin/io/nacular/doodle/layout/ConstraintLayout.kt). This can be used as follows:

```kotlin
val someContainer: Container // or a View that exposes Layout, or the Display

container.layout = constrain(child1, ... childN) { child1, ... childN ->
    child1.left = parent.left + 10
    ...
}
```

This gives fine grained control over relative positions for items that all share the same parent.

**Comment by bodiam** [comment]
Hi @pusolito ,thanks for the examples, but neither one works for me. I'm perfectly sure the issue on my end, but If I try the example using the `container` builder, the code doesn't compile:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/46468/136691026-b72575ad-8ddc-4185-9af0-0251436395e0.png">

When I try a new instance of a View (I created a subclass) the code compiles, but doesn't show anything:

```
class HelloWorld(display: Display): Application {
    init {
        display += FormView()
    }

    override fun shutdown() {}
}

class FormView() : View() {
    init {
        children += Label("Some Text")
        children += PushButton("My Button")
    }
}

fun main() {
    application {
        HelloWorld(display = instance())
    }
}
```

What am I missing here?

**Comment by bodiam** [comment]
I've attempted another one, based on the Calculator example, but also this one renders an empty screen: 

https://gist.github.com/bodiam/053e81f93b36e5b69e7e6200c7988503

**Comment by pusolito** [comment]
The issue with += for display is an IDE one. It doesn't auto import that method from the Display file for some reason. Just import plusAssign yourself. Then, things aren't showing because both Label and PushButton need a `Behavior` installed to render. These views delegate render and some other things to this pluggable strategy. 

You can use a Theme that includes items for each: https://nacular.github.io/doodle/#/themes. The BasicTheme has modules for both. Or you can install them directly to each via the `behavior` property.

**Comment by bodiam** [comment]
> The issue with += for display is an IDE one. It doesn't auto import that method from the Display file for some reason. Just import plusAssign yourself. Then, things aren't showing because both Label and PushButton need a Behavior installed to render. These views delegate render and some other things to this pluggable strategy.

Are you sure about that one? The `container` returns a Container type. `Display.plusAssign` only takes a `View` object. 

If I do the following, it compiles:

```
    init {
        val container: Iterable<View> = container {
            size = display.size
            children += Label("my text")
            children += PushButton("my buttton")
        }
        display += container
    }
```

If I inline it, it doesn't (probably because `container` returns a `Container` type?):

<img width="477" alt="image" src="https://user-images.githubusercontent.com/46468/136713987-94defd36-0cfe-4cfc-9534-ea9759f288e6.png">

What am I missing here?

**Comment by pusolito** [comment]
Container is a View though: https://github.com/nacular/doodle/blob/master/Core/src/commonMain/kotlin/io/nacular/doodle/core/Container.kt. Will have to investigate this more when at my computer later during the week.

**Comment by bodiam** [comment]
Hmm, good point. I'll do some more investigation myself, I'll let you know how I go.

Btw, I'm sorry for the amount of questions I have, but I appreciate your support!

**Comment by pusolito** [comment]
Ah, I think I've seen this a few times and it's an ambiguous resolution issue. `Display` is also an `Iterable`. So the compiler gets confused. The work-around I've used is typing out the full call at the site. Then replacing it with the operator: `display.plusAssign(container {})` then change back.

This is a total hack, and should actually be filed as a bug with Jetbrains if it is the case.

**Comment by bodiam** [comment]
@pusolito I've tried the hack, but IntelliJ doesn't seem to like it. 

<img width="818" alt="image" src="https://user-images.githubusercontent.com/46468/136722192-b12d9e2a-f794-4f23-8a36-d1e0ab89cbe3.png">

**Comment by bodiam** [comment]
I've tried using one of your examples from here: https://nacular.github.io/doodle/#/themes

This one:

```
class MyApp(display: Display,
            manager: ThemeManager,
            theme  : NativeTheme): Application {

    init {
        manager.selected = theme
    }
}

fun main() {
    application(modules = listOf(NativeTheme)) {
        MyApp(instance(), instance(), instance())
    }
}
```

But besides missing the shutdown method, the listOf(NativeTheme) also doesn't work. Not sure how to fix.

<img width="719" alt="image" src="https://user-images.githubusercontent.com/46468/136762389-19d34f4a-e931-49f5-85d4-74ca638d5142.png">

**Comment by bodiam** [comment]
Now we're getting somewhere:

<img width="410" alt="image" src="https://user-images.githubusercontent.com/46468/136940870-4f082439-ff56-4ceb-825e-785bdbd6dee8.png">

```kotlin
import io.nacular.doodle.application.Application
import io.nacular.doodle.application.Modules.Companion.FontModule
import io.nacular.doodle.application.application
import io.nacular.doodle.controls.buttons.PushButton
import io.nacular.doodle.controls.panels.GridPanel
import io.nacular.doodle.controls.text.Label
import io.nacular.doodle.core.*
import io.nacular.doodle.drawing.FontLoader
import io.nacular.doodle.geometry.Size
import io.nacular.doodle.layout.constrain
import io.nacular.doodle.theme.ThemeManager
import io.nacular.doodle.theme.adhoc.DynamicTheme
import io.nacular.doodle.theme.basic.BasicTheme.Companion.basicButtonBehavior
import io.nacular.doodle.theme.basic.BasicTheme.Companion.basicLabelBehavior
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch
import org.kodein.di.instance

class GridPanelLabelDemo(
    display: Display,
    fonts: FontLoader,
    themeManager: ThemeManager,
    theme: DynamicTheme
) : Application {
    init {
        GlobalScope.launch {
            val font = fonts {
                family = "Arial"
                size = 20
            }

            themeManager.selected = theme

            val label = Label("Some Text").apply {
                this.font = font
                size = Size(300, 40)
            }

            val button = PushButton("Some Button").apply {
                this.font = font
                size = Size(200, 40)

                fired += {
                    println("Hey! That Hurt!")
                }
            }

            val views: Iterable<View> = listOf(label, button)

            val buttonSpacing =  10.0
            val outputHeight  = 100.0

            val gridPanel = GridPanel().apply {
                add(label, 0, 0);
                add(button, 1, 0);

                verticalSpacing   = { buttonSpacing }
                horizontalSpacing = { buttonSpacing }
            }

            display += listOf(gridPanel)

            // Place output outside grid so the height can be more easily controlled
            val constraints = constrain(gridPanel) { grid ->
                grid.top      = parent.bottom + buttonSpacing
                grid.left     = parent.left
                grid.right    = parent.right
                grid.bottom   = parent.bottom
            }
            
            display += views

            display.layout = object: Layout by constraints {
                // Set total height to grid panel's ideal width and height, plus output and spacing
                override fun idealSize(container: PositionableContainer, default: Size?) = gridPanel.idealSize?.let {
                    Size(it.width, it.height + outputHeight + buttonSpacing)
                }
            }
        }
    }

    override fun shutdown() {}
}


fun main() {
    val appModules = listOf(basicLabelBehavior(), basicButtonBehavior(), FontModule)

    application(modules = appModules) {
        GridPanelLabelDemo(instance(), instance(), instance(), instance())
    }
}
```

Current issues however:

* I can't get clicking of the button to work. I can't click on it, even though I have a `fired` property on it. 

Any tips?
