### ISSUE TITLE
Search in documentation not working well

### ISSUE THREAD

**Issue by bodiam** [nacular/doodle#19]
I'm not sure how the search works in the documentation, but it seems to not work well. When I search for "Layout", I'm getting a lot of 404 errors:

<img width="866" alt="image" src="https://user-images.githubusercontent.com/46468/136682884-382a108a-f11c-438e-8f49-0cb0a7283c27.png">

(The Buttons gives a 404, and so does Defining our application, The Application, etc)

**Comment by pusolito** [comment]
Will take a look.

**Comment by pusolito** [comment]
Documentation no longer uses docsify, so this issue is no longer relevant.
