### ISSUE TITLE
Inputs not working on iPhone 6

### ISSUE THREAD

**Issue by hiperbou** [nacular/doodle#3]
Using an iPhone 6S 12.1.3, Chrome and Safari browsers.

It seems like the input is not working on any of the UI Components examples:
https://nacular.github.io/doodle/#/controls

**Comment by pusolito** [comment]
This could be due to a lack of PointerEvent support on older browsers. Mobile Safari only supported this in IOS 13 it seems. What version of Chrome is the device running?

**Comment by hiperbou** [comment]
It could make sense since I'm still using iOS 12 on this device.
By the way my Chrome version is 86.0.4240.93.
