### ISSUE TITLE
Not found docs source code

### ISSUE THREAD

**Issue by icode** [nacular/doodle#33]
Documents not open source?

**Comment by pusolito** [comment]
Do you mean for the apps within the documentation? Those are not in a public repo yet; mostly because the code is far less commented 😅.

Have you see. the [tutorials](https://nacular.github.io/doodle-tutorials/)? The source for those apps os [available](https://github.com/nacular/doodle-tutorials).

**Comment by icode** [comment]
> Do you mean for the apps within the documentation? Those are not in a public repo yet; mostly because the code is far less commented 😅.
> 
> Have you see. the [tutorials](https://nacular.github.io/doodle-tutorials/)? The source for those apps os [available](https://github.com/nacular/doodle-tutorials).

emmm, the `/docs` path source code, markdown files?

**Comment by pusolito** [comment]
They aren't right now. But maybe at some point they will be.
