### ISSUE TITLE
Horizontal scrollbars shouldn't appear in some examples

### ISSUE THREAD

**Issue by hiperbou** [nacular/doodle#38]
I noticed a consistent behavior with the scrollbars that might be not desireable in the UI Components overview (https://nacular.github.io/doodle/docs/ui_components/overview)

The examples that contain a vertical scroll the view's width is not well adjusted and an horizontal scrollbar appears.

On Windows 10, latest Firefox and Chrome

![scrollbars](https://user-images.githubusercontent.com/12442874/178098345-74564db7-e68d-46f0-a7a6-9008494f15f9.jpg)

![scrollbars2](https://user-images.githubusercontent.com/12442874/178098443-d028dedf-45d6-4a5b-b194-aa6fe4b02794.jpg)

![scrollbars3](https://user-images.githubusercontent.com/12442874/178098447-a6123024-5b21-4a62-bfbd-78eafbdb888f.jpg)

![scrollbars4](https://user-images.githubusercontent.com/12442874/178098466-b380145a-4367-4cc0-9828-f7db820432bd.jpg)

**Comment by pusolito** [comment]
This is a good point. I'll see how to make it easier for the content width and height constraints to incorporate the bar sizes. That way a caller can create the behavior you mentioned.
