### ISSUE TITLE
How to make native window menus?

### ISSUE THREAD

**Issue by emanuelfranklyn** [nacular/doodle#59]
I'm trying to make an exclusive desktop app to handle some things on my pc, and would like for the app to have a menu bar at the top with some actions.

And I know there is a component called menu, it however draws to the canvas (feature that made me choose this lib over other options that use native API calls to draw components).

And while it is possible to manually draw the bar to the screen, I would like for this bar to specifically use the native menu API.

This way, the elements can appear at my system's top bar instead of being a bar below the system's top bar.

Is that possible? To have the application window to call the native system menu handler to add options?

**Comment by pusolito** [comment]
This functionality is planned, but doesn't exist in the current version of the lib. Thanks for filing this issue; it helps to confirm the need for this sooner than later.

**Comment by pusolito** [comment]
i just shared an [update](https://kotlinlang.slack.com/archives/C01CJM07MGV/p1705076786701079) in Doodle's Kotlin Slack channel about progress toward 0.10.0.

there is a video showing an early prototype for multi-window support. apps would have access to a new type for window management that enables customization and creation of windows, creating/managing OS menu bars etc.. this work is still early, but wanted to share the direction so far.

**Comment by emanuelfranklyn** [comment]
I cannot access the slack page, however I have been experimenting with native API calls on c++, not sure how macOS handles global menus, but on Linux this is handled using a thing called dbus, and you can use it to send menu data to Canonical appmenu system, and because of compatibility layers it should pretty much every distro with global menus, I don't know if windows have a native window menu system, but from what people online have been saying about this issue, what apps normally do is check if there's any global menu (if it is macOS or Linux with global menu) and if it does, it just don't show the bar, but if it draws a custom menu bar (for the design flexibility of handling menus as drawable elements).

I don't know how you're handling this issue, I'm just explaining this because it took a while and lots of research to figure out this (mostly how the canonical app menu and dbus part works), this should be able to be implemented by itself without depending on the UI framework actually, haven't tested it out tho.

Happy to see multi-window support, looks very promising.

**Comment by pusolito** [comment]
i think native me is should be doable using the underlying AWT layer. i'll show this working in an update soon.

you should be able to get into the Slack via this http://slack.kotl.in/

**Comment by pusolito** [comment]
This is now possible with the latest release: https://nacular.github.io/doodle/docs/whatsnew#native-window-menus.
