### ISSUE TITLE
Doodle vs Compose Multiplatform UI

### ISSUE THREAD

**Issue by RAbraham** [nacular/doodle#61]
Hi,
apologies for the newbie question. How is Doodle different from Compose Multiplatform? 
https://www.jetbrains.com/lp/compose-multiplatform/
Thanks!

**Comment by pusolito** [comment]
No worries. This is a valid question. Check out the answer I shared before when this came up in the Doodle Slack channel:  https://kotlinlang.slack.com/archives/C01CJM07MGV/p1676435396815939. Go to http://slack.kotl.in for instructions on getting an invitation if you aren't already able to access.

**Comment by RAbraham** [comment]
Thanks a lot!
