### ISSUE TITLE
Is there a Dropdown component available?

### ISSUE THREAD

**Issue by epragtpks** [nacular/doodle#9]
I had a look at the documentation, and I was wondering if a dropdown component was available as an input? 

I saw the list item, and input item, but no dropdown. Thanks!

**Comment by pusolito** [comment]
There isn't one yet. Thanks for pointing this out.

**Comment by epragtpks** [comment]
Hi @pusolito, cheers, thanks for that. I'll have a look at how I go, I was thinking of trying out Nacular for a small utility I'm building (was JavaFX, now Swing, and I considered Compose), and in that regard, Nacular seemed interesting. Thanks!

**Comment by pusolito** [comment]
Sounds good. I'd love to hear any feedback you have as you work through it. And please continue filing issues when you run across them.
